FROM alpine:3.18.4

ARG USER_UID=1000
ARG GROUP_GID=1000
ARG UGNAME=nonroot

WORKDIR /data

# Create a new system group and a new system user with the specified UID, GID, and username.
RUN addgroup --system --gid ${GROUP_GID} ${UGNAME}

RUN adduser --system --disabled-password --home /home/${UGNAME} \
    --uid ${USER_UID} --ingroup ${UGNAME} ${UGNAME}

RUN apk update \
 && apk upgrade --no-cache \
 && apk --no-cache add xz gzip mtools qemu-img

COPY entrypoint.processor.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER ${UGNAME}

ENTRYPOINT ["/entrypoint.sh"]
