version: '3.8'

services:
  change-vol-ownership:
    # We can use any image we want as long as we can chown
    image: alpine:3.18.4
    # Need a user priviliged enough to chown
    user: "root"
    # Specify the group in question
    group_add:
      - ${GROUP_GID}
    volumes:
      # The volume to chown
      - data-volume:/data
    command: chown -R ${USER_UID}:${GROUP_GID} /data

  downloader:
    image: greenukr/downloader:0.2.0
    build:
      context: ./downloader
      dockerfile: Dockerfile.downloader
      args:
        - DEFAULT_UID=${USER_UID}
        - DEFAULT_GID=${GROUP_GID}
        - DEFAULT_GUNAME=${UG_NAME}
    working_dir: /data
    volumes:
      - data-volume:/data
    env_file:
      - .env
      - .downloader.env
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully

  processor:
    image: greenukr/processor:0.2.0
    build:
      context: ./processor
      dockerfile: Dockerfile.processor
    working_dir: /data
    volumes:
      - data-volume:/data
    env_file:
      - .env
      - .downloader.env
      - .processor.env
    depends_on:
      downloader:
        condition: service_completed_successfully

  emulator:
    image: greenukr/emulator:0.2.0
    cpus: "4"
    mem_reservation: "2048M"
    mem_limit: "4096M"
    build:
      context: ./emulator
      dockerfile: Dockerfile.emulator

    working_dir: /data
    volumes:
      - data-volume:/data
    ports:
      - "2222:2222"
    env_file:
      - .env
      - .processor.env
    # security-opt:
    #     - no-new-privileges
    depends_on:
      processor:
        condition: service_completed_successfully
    entrypoint: qemu-system-aarch64 -name rpi3bp -machine raspi3b -cpu cortex-a72 -nographic -dtb bcm2710-rpi-3-b-plus.dtb -m 1G -smp 4 -kernel kernel8.img -sd sd.img -append "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1" -device usb-net,netdev=net0,mac=02:ca:fe:f0:0d:01 -netdev user,id=net0,hostfwd=tcp::2222-:22
    # command: ["-machine raspi3b", "-cpu cortex-a72", "-nographic", \
    #           "-dtb bcm2710-rpi-3-b-plus.dtb", "-m 1G -smp 4", \
    #           "-kernel kernel8.img", \
    #           "-sd sd.img", \
    #           "-append 'rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1'", \
    #           "-device 'usb-net,netdev=net0,mac=02:ca:fe:f0:0d:01'", \
    #           "-netdev 'user,id=net0,hostfwd=tcp::2222-:22'"]
    # command: ["-version"]
    # command: ["-readconfig", "/qemu_raspi3b_config.cfg"]
    restart: "no"
    # restart: always
    # restart: on-failure
    # restart: unless-stopped

volumes:
  data-volume:
